CREATE TABLE IF NOT EXISTS menu (
    `Item_id` INT,
    `Item_Category` VARCHAR(20) CHARACTER SET utf8,
    `Item_subcategory` VARCHAR(14) CHARACTER SET utf8,
    `Item_name1` VARCHAR(22) CHARACTER SET utf8,
    `Item_name2` VARCHAR(22) CHARACTER SET utf8,
    `Item_price` INT,
    `Item_Veg` VARCHAR(7) CHARACTER SET utf8,
    `Item_image` VARCHAR(61) CHARACTER SET utf8,
    `Item_Remarks` VARCHAR(21) CHARACTER SET utf8
);
INSERT INTO menu VALUES
    (1001,'Breads','Bread','Plain','Bread',50,'Veg','./assets/images/Products/Plain_bread.jpg',NULL),
    (1002,'Breads','Bread','Whole Wheat','Bread',60,'Veg','./assets/images/Products/Whole_Wheat_Bread_Loaf.jpg',NULL),
    (1003,'Breads','Bread','Multigrain','Bread',60,'Veg','./assets/images/Products/Multigrain_bread.jpg',NULL),
    (1004,'Breads','Bread','Hazelnut ','Bread Loaf',60,'Non Veg','./assets/images/Products/Hazelnut_bread.jpg',NULL),
    (1005,'Breads','Bread','Brown','Bread  Loaf',50,'Veg','./assets/images/Products/Brown_bread.jpg',NULL),
    (1006,'Breads','Bread','Garlic','Bread',100,'Veg','./assets/images/Products/Garlic_bread.jpg',NULL),
    (1007,'Breads','Bread','Sandwich','Bread',80,'Veg','./assets/images/Products/Sandwich_Bread.jpg',NULL),
    (1008,'Breads','Artisans Bread','German Rye Walnut','Artisans Bread',100,'Veg','./assets/images/Products/Artisans_Bread_German_Rye_Walnut.jpg',NULL),
    (1009,'Breads','Artisans Bread','Seven Cereals','Artisans Bread',100,'Veg','./assets/images/Products/Artisans_Bread_Seven_Cereals.jpg',NULL),
    (1010,'Breads','Artisans Bread','Ciabatta','Artisans Bread',100,'Veg','./assets/images/Products/Cibatta_Bread.jpg',NULL),
    (1011,'Breads','Focaccia','Rosemary & Olive','Focaccia',80,'Veg','./assets/images/Products/Foccacia.jpg',NULL),
    (1012,'Breads','Focaccia','Sundried Tomato','Oregano Focaccia',80,'Veg','./assets/images/Products/Foccacia.jpg',NULL),
    (1013,'Breads','Bun','Burger Bun','(pack of 4)',100,'Veg','./assets/images/Products/Burger_bun.jpg',NULL),
    (1014,'Breads','Bun','Hot Dog Bun','(pack of 3)',75,'Veg','./assets/images/Products/Hot_Dog_Buns.jpg',NULL),
    (1015,'Breads','Bun','Pav Bun','(pack of 6)',50,'Veg','./assets/images/Products/Paav_bun.jpg',NULL),
    (1016,'Breads','Baguette','Baguette','(Plain)',100,'Veg','./assets/images/Products/Baugette.jpg',NULL),
    (1017,'Breads','Baguette','Baguette','(Herbs)',100,'Veg','./assets/images/Products/Baugette_herbs.jpg',NULL),
    (1018,'Breads','Special Bread','Sour Dough','Bread',150,'Veg','./assets/images/Products/Sour_Dough_Sliced.jpg','Made on Order only'),
    (1019,'Breads','Special Bread','Quinoa Burger Buns','Buns',120,'Veg','./assets/images/Products/Qimuoa_Burger_buns.jpg','Made on Order only'),
    (1020,'Breads','Special Bread','Leavened Bread','(coriander & onion)',80,'Veg','./assets/images/Products/Kulcha_bread.jpg','Made on Order only'),
    (1021,'Morning_Bakery','Croissant','Butter','Croissant',90,'Veg','./assets/images/Products/Butter_croissant.jpg',NULL),
    (1022,'Morning_Bakery','Croissant','Chocolate Croissant','(Pain Au Chocolat)',100,'Veg','./assets/images/Products/Multigrain_croissant.jpg',NULL),
    (1023,'Morning_Bakery','Croissant','Almond','Croissant',150,'Non Veg','./assets/images/Products/Almond_croissant.jpg',NULL),
    (1024,'Morning_Bakery','Muffin','Blueberry','Muffin',90,'Non Veg','./assets/images/Products/Blueberry_muffin.jpg',NULL),
    (1025,'Morning_Bakery','Muffin','Chocolate','Muffin',90,'Non Veg','./assets/images/Products/Chocolate_Muffin.jpg',NULL),
    (1026,'Morning_Bakery','Donut','Sugar & Cinnamon','Donut',100,'Non Veg','./assets/images/Products/Pink_Chocolate_Donut.jpg',NULL),
    (1027,'Morning_Bakery','Donut','Chocolate ','Donut',120,'Non Veg','./assets/images/Products/Chocolate_Donut.jpg',NULL),
    (1028,'Morning_Bakery','Donut','Jam','Berliner',100,'Non Veg','./assets/images/Products/Berliner.jpg',NULL),
    (1029,'Morning_Bakery','Donut','Chocolate','Berliner',120,'Non Veg','./assets/images/Products/Berliner_chocolate.jpg',NULL),
    (1030,'Morning_Bakery','Danish Pastry','Blueberry','Danish',100,'Veg','./assets/images/Products/Danish_Pastry.jpg',NULL),
    (1031,'Morning_Bakery','Danish Pastry','Almond Cream','Danish',100,'Non Veg','./assets/images/Products/Danish_Pastry.jpg',NULL),
    (1032,'Morning_Bakery','Danish Pastry','Chocolate & Walnut','Danish',100,'Veg','./assets/images/Products/Danish_Pastry.jpg',NULL),
    (1033,'Savouries','Pretzel','Soft','Pretzels',35,'Veg','./assets/images/Products/Pretzels.jpg','Made on Order only'),
    (1034,'Savouries','Puff','Vegetable','Puff',55,'Veg','./assets/images/Products/Puffs.jpg',NULL),
    (1035,'Savouries','Puff','Paneer Matar','Puff',65,'Veg','./assets/images/Products/Paneer_Matar_Puff.jpg',NULL),
    (1036,'Savouries','Puff','Chicken','Puff',65,'Non Veg','./assets/images/Products/Puffs.jpg',NULL),
    (1037,'Savouries','Puff','Mutton Galawati','Puff',120,'Non Veg','./assets/images/Products/Mutton_Keema_Puff.jpg',NULL),
    (1038,'Savouries','Puff','Mutton Keema','Puff',120,'Non Veg','./assets/images/Products/Mutton_Keema_Puff.jpg',NULL),
    (1039,'Savouries','Sandwich','Chicken Grilled','Sandwich',65,'Non Veg','./assets/images/Products/Chicken_Grilled_Sandwich.jpg',NULL),
    (1040,'Savouries','Sandwich','Veg Grilled','Sandwich',55,'Veg','./assets/images/Products/Veg_Grilled_Sandwich_1.jpg',NULL),
    (1041,'Savouries','Sandwich','Criossant','Sandwich',65,'Non Veg','./assets/images/Products/Croissant_Sandwich.jpg',NULL),
    (1042,'Savouries','Sandwich','Foccacia','Sandwich',65,'Non Veg','./assets/images/Products/Focaccia_Sandwich.jpg',NULL),
    (1043,'Savouries','Quiche','Vegetable','Quiche',70,'Veg','./assets/images/Products/Vegetable_Quiche.jpg',NULL),
    (1044,'Savouries','Quiche','Chicken','Quiche',80,'Non Veg','./assets/images/Products/Chicken_Quiche.jpg',NULL),
    (1045,'Morning_Bakery','Cake Slice','Red Velvet','Slice',225,'Veg','./assets/images/Products/Red_Velvet_slice.jpg',NULL),
    (1046,'Morning_Bakery','Cake Slice','Mississippi Mud','Slice',225,'Non Veg','./assets/images/Products/Choco_Mudslice_Pastry.jpg',NULL),
    (1047,'Pastries','Brownie','Original Chocolate','Brownie',100,'Veg','./assets/images/Products/Brownie.jpg',NULL),
    (1048,'Pastries','Brownie','Milk Chocolate chip','Brownie',100,'Veg','./assets/images/Products/Brownie.jpg',NULL),
    (1049,'Pastries','Brownie','Caramel','Brownie',100,'Veg','./assets/images/Products/Brownie.jpg',NULL),
    (1050,'Pastries','Brownie','Hazelnut','Brownie',100,'Veg','./assets/images/Products/Brownie.jpg',NULL),
    (1051,'Pastries','Pastries','Belgian Chocolate','Truffle Pastry',140,'Veg','./assets/images/Products/Dark_Chocolate_Truffle_Pastry.jpg',NULL),
    (1052,'Pastries','Pastries','Opera','Pastry',140,'Non Veg','./assets/images/Products/Opera_Pastry_1.jpg',NULL),
    (1053,'Pastries','Pastries','Chocolate & Cherry','Pastry',120,'Veg','./assets/images/Products/Chocolate_Cherry_Pastry.jpg',NULL),
    (1054,'Pastries','Pastries','Peach & Pineapple','Pastry',120,'Veg','./assets/images/Products/Peach_&_Pineapple_Pastry_1.jpg',NULL),
    (1055,'Pastries','Pastries','Hazelnut Magnum','Pastry',140,'Non Veg','./assets/images/Products/Hazelnut_Magnum_1.jpg',NULL),
    (1056,'Pastries','Pastries','Mango Passion','Dome Pastry',120,'Non Veg','./assets/images/Products/Mango_Passion_Dome.jpg',NULL),
    (1057,'Pastries','Pastries','Seasonal Fruit','Tart',140,'Veg','./assets/images/Products/Seasonal_Fruit_Tart_1.jpg',NULL),
    (1058,'Pastries','Pastries','NewYork Baked Cheese','Pastry',140,'Non Veg','./assets/images/Products/NewYork_Baked_Cheese_Pastry_1.jpg',NULL),
    (1059,'Pastries','Pastries','Lemon Meringue','Tart Pastry',120,'Non Veg','./assets/images/Products/Lemon_Meringue_Tart.jpg',NULL),
    (1060,'Pastries','Pastries','Chocolate Ferrero','Eclairs',120,'Non Veg','./assets/images/Products/Choco_Ferrero_Eclairs.jpg',NULL),
    (1061,'Pastries','Pastries','Coffee Gianduja','Eclairs',120,'Non Veg','./assets/images/Products/Coffee_Gianduja_Eclairs.jpg',NULL),
    (1062,'Pastries','Pastries','Brownie','Pastry',120,'Non Veg','./assets/images/Products/Brownie_pastry.jpg',NULL),
    (1063,'Pastries','Pastries','Choco Mud Slice','Pastry',120,'Non Veg','./assets/images/Products/Choco_Mudslice_Pastry.jpg',NULL),
    (1064,'Pastries','Pastries','Seasonal Fruit ','Tart',150,'Veg','./assets/images/Products/Mango_fruit_tart.jpg',NULL),
    (1065,'Pastries','Pastries','Red Velvet','Pastry',140,'Veg','./assets/images/Products/Red_Velvet_Pastry.jpg',NULL),
    (1066,'Signature_Collection','Cakes','Blueberry Cheese','Cake (1 Kg)',1500,'Non Veg','./assets/images/Products/Blueberry_Cheesecake.jpg',NULL),
    (1067,'Signature_Collection','Cakes','Mango Cheese','Cake (1 Kg)',1500,'Non Veg','./assets/images/Products/Mango_cheesecake.jpg',NULL),
    (1068,'Signature_Collection','Cakes','Opera','Cake (1 Kg)',1500,'Non Veg','./assets/images/Products/Opera_Cake_1.jpg',NULL),
    (1069,'Signature_Collection','Cakes','Tiramisu','Cake (1 Kg)',1500,'Non Veg','./assets/images/Products/Tiramisu_Cake_2.jpg',NULL),
    (1070,'Signature_Collection','Cakes','Seasonal Fruit','Cake (1 Kg)',1500,'Veg','./assets/images/Products/Seasonal_Fresh_Fruit_Cake.jpg',NULL),
    (1071,'Signature_Collection','Cakes','Mango Charlotte','Cake (1 Kg)',1500,'Non Veg','./assets/images/Products/Z_logo.jpeg',NULL),
    (1072,'Signature_Collection','Cakes','Hazelnut Magnum','Cake (1 Kg)',1500,'Non Veg','./assets/images/Products/Hazelnut_Magnum_Cake.jpg',NULL),
    (1073,'Signature_Collection','Cakes','Blueberry Cheese','Cake (500 Gm)',750,'Non Veg','./assets/images/Products/Blueberry_Cheesecake.jpg',NULL),
    (1074,'Signature_Collection','Cakes','Mango Cheese','Cake (500 Gm)',750,'Non Veg','./assets/images/Products/Mango_cheesecake1.jpg',NULL),
    (1075,'Signature_Collection','Cakes','Opera','Cake (500 Gm)',750,'Non Veg','./assets/images/Products/Opera_Cake_2.jpg',NULL),
    (1076,'Signature_Collection','Cakes','Tiramisu','Cake (500 Gm)',750,'Non Veg','./assets/images/Products/Tiramisu_Cake_1.jpg',NULL),
    (1077,'Signature_Collection','Cakes','Seasonal Fruit','Cake (500 Gm)',750,'Veg','./assets/images/Products/Seasonal_Fresh_Fruit_Cake_1.jpg',NULL),
    (1078,'Signature_Collection','Cakes','Mango Charlotte','Cake (500 Gm)',750,'Non Veg','./assets/images/Products/Z_logo.jpeg',NULL),
    (1079,'Signature_Collection','Cakes','Hazelnut Magnum','Cake (500 Gm)',750,'Non Veg','./assets/images/Products/Hazelnut_Magnum_Cake1.jpg',NULL),
    (1080,'Cakes','Cakes','Belgium Chocolate','Truffle Cake (1 Kg)',1350,'Veg','./assets/images/Products/Belgian_Chocolate_Truffle_Cake.jpg',NULL),
    (1081,'Cakes','Cakes','Chocolate & Cherry','Cake(1 Kg)',1200,'Veg','./assets/images/Products/Chocolate_&_Cherry_Cake.jpg',NULL),
    (1082,'Cakes','Cakes','Red Velvet','Cake (1 Kg)',1350,'Veg','./assets/images/Products/Red_Velvet_Cake.jpg',NULL),
    (1083,'Cakes','Cakes','New York Baked ','Cheese Cake (1 Kg)',1350,'Non Veg','./assets/images/Products/New_York_Baked_Cheesecake.jpg',NULL),
    (1084,'Cakes','Cakes','Mango Caramel','Cake (1 Kg)',1350,'Non Veg','./assets/images/Products/Z_logo.jpeg',NULL),
    (1085,'Cakes','Cakes','Chocolate Mango','Cake (1 Kg)',1350,'Veg','./assets/images/Products/Z_logo.jpeg',NULL),
    (1086,'Cakes','Cakes','Peach & Pineapple','Cake (1 Kg)',1200,'Veg','./assets/images/Products/Peach_&_Pineapple_Cake.jpg',NULL),
    (1087,'Cakes','Cakes','Belgium Chocolate ','Truffle Cake (500 Gm)',675,'Veg','./assets/images/Products/Belgian_Chocolate_Truffle_Cake.jpg',NULL),
    (1088,'Cakes','Cakes','Chocolate & Cherry','Cake (500 Gm)',600,'Veg','./assets/images/Products/Chocolate_&_Cherry_Cake.jpg',NULL),
    (1089,'Cakes','Cakes','Red Velvet','Cake (500 Gm)',675,'Veg','./assets/images/Products/Red_velvet_cake1.jpg',NULL),
    (1090,'Cakes','Cakes','New York Baked','Cheese Cake (500 Gm)',675,'Non Veg','./assets/images/Products/New_York_Baked_Cheesecake_2.jpg',NULL),
    (1091,'Cakes','Cakes','Mango Caramel','Cake (500 Gm)',675,'Non Veg','./assets/images/Products/Z_logo.jpeg',NULL),
    (1092,'Cakes','Cakes','Chocolate Mango','Cake (500 Gm)',675,'Veg','./assets/images/Products/Z_logo.jpeg',NULL),
    (1093,'Cakes','Cakes','Peach & Pineapple','Cake (500 Gm)',600,'Veg','./assets/images/Products/Peach_&_Pineapple_Cake.jpg',NULL),
    (1094,'Cakes','Special Cakes','Designer Cream','Cake-Eggless (per  Kg)',2000,'Veg','./assets/images/Products/Designer_cake1.jpg','Minimum order two kgs'),
    (1095,'Cakes','Special Cakes','Designer Cream','Cake (per Kg)',2000,'Non Veg','./assets/images/Products/Designer_cake_1_1.jpg','Minimum order two kgs'),
    (1096,'Cakes','Special Cakes','Fondant','Cake (per Kg)',2700,'Non Veg','./assets/images/Products/Z_logo.jpeg','Minimum order two kgs'),
    (1097,'Cakes','Cupcakes','Red Velvet','Cup Cake',80,'Veg','./assets/images/Products/Red_velvet_cupcake.jpg',NULL),
    (1098,'Cakes','Cupcakes','Strawberry Rose','Cup Cake',80,'Veg','./assets/images/Products/Strawberry_rose_cupcake.jpg',NULL),
    (1099,'Cakes','Cupcakes','Tiramisu','Cup Cake',80,'Veg','./assets/images/Products/Tiramisu_Cupcake.jpg',NULL),
    (1100,'Cakes','Cupcakes','Chocolate Oreo','Cup Cake',80,'Veg','./assets/images/Products/Chocolate_Oreo_Cupcake.jpg',NULL),
    (1101,'Cakes','Cupcakes','Lemon Citrus','Cup Cake',80,'Veg','./assets/images/Products/Lemon_Citrus_Cupcakes.jpg',NULL),
    (1102,'Cakes','Cupcakes','Blueberry','Cup Cake',80,'Veg','./assets/images/Products/Blueberry_Cupcake.jpg',NULL),
    (1103,'Cakes','Tea cake','Banana Walnut','Tea Cake',350,'Non Veg','./assets/images/Products/Tea_Cake.jpg',NULL),
    (1104,'Cakes','Tea cake','English Fruit','Tea Cake',375,'Non Veg','./assets/images/Products/Tea_Cake.jpg',NULL),
    (1105,'Cakes','Tea cake','Peanut Butter & Coffee','Tea Cake',375,'Non Veg','./assets/images/Products/Tea_Cake.jpg',NULL),
    (1106,'Cakes','Tea cake','Marble','Tea Cake',375,'Non Veg','./assets/images/Products/Tea_Cake.jpg',NULL),
    (1107,'Puddings','Pudding','Black Forest','Pudding',150,'Veg','./assets/images/Products/Blackforest_pudding.jpg',NULL),
    (1108,'Puddings','Pudding','Red Velvet','Pudding',150,'Veg','./assets/images/Products/Red_Velvet_Pudding_Jar.jpg',NULL),
    (1109,'Puddings','Pudding','Tiramisu','Pudding',150,'Non Veg','./assets/images/Products/Tiramisu_Pudding_Jar.jpg',NULL),
    (1110,'Puddings','Pudding','Choco-Cherry','Pudding',150,'Non Veg','./assets/images/Products/Chocolate_&_Cherry_Pudding_Jar.jpg',NULL),
    (1111,'Macaroons','Macroon','Raspberry-Vanilla','Macaroons',60,'Non Veg','./assets/images/Products/Raspberry_vanilla_macaroons.jpg',NULL),
    (1112,'Macaroons','Macroon','Limoncello','Macaroons',60,'Non Veg','./assets/images/Products/Macaroons.jpg',NULL),
    (1113,'Macaroons','Macroon','Belgium Chocolate','Macaroons',60,'Non Veg','./assets/images/Products/Macaroons_1.jpg',NULL),
    (1114,'Macaroons','Macroon','Raspberry-Choco','Macaroons',60,'Non Veg','./assets/images/Products/Raspberry_vanilla_macaroons.jpg',NULL),
    (1115,'Macaroons','Macroon','Salted Caramel','Macaroons',60,'Non Veg','./assets/images/Products/Macaroons_3.jpg',NULL),
    (1116,'Macaroons','Macroon','Mint & Chocolate','Macaroons',60,'Non Veg','./assets/images/Products/Macaroons_4.jpg',NULL),
    (1117,'Assortments','Cookies','Chocolate Chip','Cookies (Pack of 6)',90,'Non Veg','./assets/images/Products/Cookies.jpg',NULL),
    (1118,'Assortments','Cookies','Peanut Butter','Cookies (Pack of 6)',90,'Non Veg','./assets/images/Products/Cookies.jpg',NULL),
    (1119,'Assortments','Cookies','Vanilla Sable','Cookies (Pack of 6)',90,'Non Veg','./assets/images/Products/Cookies.jpg',NULL),
    (1120,'Assortments','Cookies','Oatmeal Raisin','Cookies (Pack of 6)',90,'Non Veg','./assets/images/Products/Cookies.jpg',NULL),
    (1121,'Assortments','Cookies','Molten Chocolate','Cookies (Pack of 6)',90,'Non Veg','./assets/images/Products/Cookies.jpg',NULL),
    (1122,'Assortments','Chocolate','Hand Pressed','Chocolate Pack ( 6)',250,'Veg','./assets/images/Products/Handpressed_Chocolates.jpg',NULL),
    (1123,'Assortments','Chocolate','Hand Pressed','Chocolate Pack (12)',500,'Veg','./assets/images/Products/Handpressed_Chocolates.jpg',NULL),
    (1124,'Assortments','Coffee','Coffee','Cappuccino',100,'Veg','./assets/images/Products/Capuccino.jpg',NULL),
    (1125,'Assortments','Coffee','Coffee','Americano',100,'Veg','./assets/images/Products/Cafe_americano.jpg',NULL),
    (1126,'Assortments','Coffee','Coffee','Latte',100,'Veg','./assets/images/Products/Cafe_latte.jpg',NULL),
    (1127,'Assortments','Coffee','Coffee','Espresso',100,'Veg','./assets/images/Products/Cafe_espresso.jpg',NULL),
    (1128,'Assortments','Beverage','Mineral','Water',35,'Veg','./assets/images/Products/Mineral_water.jpg',NULL);
